version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - samturrell
  ignore:
  - dependency-name: "@adonisjs/fold"
    versions:
    - 8.1.0
  - dependency-name: "@adonisjs/ace"
    versions:
    - 6.8.4
